apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{.Chart.Name}}-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{.Chart.Name}}
  replicas: {{.Values.replicas }} # tells deployment to run 3 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: {{ .Release.Name }}-{{.Chart.Name}}
    spec:
      containers:
        - name: {{ .Release.Name }}-{{.Chart.Name}}
          image: {{ .Values.image }}
          ports:
            - containerPort: 8080
