apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-spring-boot-deployment
spec:
  selector:
    matchLabels:
      app: sample-spring-boot
  replicas: 2 # tells deployment to run 3 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: sample-spring-boot
    spec:
      containers:
        - name: sample-spring-boot
          image: studallianz/sample-spring-boot:latest
          ports:
            - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: sample-spring-boot-service
spec:
  selector:
    app: sample-spring-boot
  ports:
    - port: 8080
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: sample.info
      http:
        paths:
          - path: /spring-boot
            backend:
              serviceName: sample-spring-boot-service
              servicePort: 8080