node('maven') {
    stage('Checkout'){
        git('https://github.com/studallianz/sample-spring-boot')
    }
    stage('Build'){
        sh('mvn clean package')
    }
    post {
        always {
            junit 'build/reports/**/*.xml'
        }
    }
}