node('maven') {
    stage('Checkout'){
        git('https://github.com/studallianz/sample-spring-boot')
    }
    stage('Build jar'){
        sh('mvn clean package')
    }

    stage('Build image'){
        sh('docker build -t sample-spring-boot .')
    }
}