node('maven') {
    stage('Checkout'){
        git('https://github.com/studallianz/sample-spring-boot')
    }
    stage('Build jar'){
        sh('mvn clean package')
    }

    stage('Build image'){
        sh('oc start-build mavenapp -n sample-spring-boot --from-dir . --follow')
    }
}