apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{.Chart.Name}}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: {{ .Release.Name }}-{{.Chart.Name}}-service
    servicePort: 8080
  rules:
    - host: {{.Values.ingress.host}}
      http:
        paths:
          - path: {{.Values.ingress.path}}
            backend:
              serviceName: {{ .Release.Name }}-{{.Chart.Name}}-service
              servicePort: 8080